# Generated by Django 4.2.2 on 2023-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myusers", "0008_alter_newuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
