# Generated by Django 4.2.2 on 2023-06-24 01:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update="True",
                default="default",
                editable=False,
                max_length=100,
                populate_from=("post", "author", "content"),
                unique_with=("name",),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
