# Generated by Django 4.2.2 on 2023-06-24 03:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_comment_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update="True",
                editable=False,
                max_length=100,
                populate_from=("post__title", "author__username", "content"),
                unique_with=("post__title",),
            ),
        ),
    ]
