# Generated by Django 4.2.2 on 2023-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
    ]
